name: mcass_kaz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Core geospatial packages - install these with conda
  - gdal=3.10
  - cartopy=0.24.0
  - fiona=1.10.1
  - rasterio=1.4.3
  - geopandas=1.0.1
  - spatialpandas=0.5.0
  - shapely=2.1.0
  - pyproj=3.7.1
  - xarray=2025.3.1
  - rioxarray=0.19.0
  - netcdf4=1.7.2
  # Visualization packages
  - matplotlib=3.10.1
  - bokeh=3.7.2
  - holoviews=1.20.2
  - geoviews=1.14.0
  - panel=1.6.2
  - hvplot=0.11.2
  # Data processing
  - numpy=2.2.5
  - pandas=2.2.3
  - scipy=1.15.2
  - dask=2025.4.0
  # Dependencies with binary components
  - pillow=11.1.0
  - libtiff=4.7.0
  - pip=25.0.1
  - pip:
    - -r pip_requirements.txt  # Install remaining packages via pip